/**
 * @file macros.hh
 * @author Andres Coronado (andres.coronado@bss.group)
 * @brief Defines the DataModel used by the application.
 * @version 0.1
 * @date 2024-03-07
 *
 * @copyright Copyright (c) 2024
 *
 */

/**
 * @brief Macro to define the quit routine.
 *
 */
#define QUIT_ROUTINE()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
  if(this->quitRequested)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
      wxGetApp().CallAfter([this] {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \
        this->workerThread.join();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
        this->processing    = false;                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
        this->quitRequested = false;                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
        this->Destroy();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
      });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
      return;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
    }