# setting directories
set_property(GLOBAL PROPERTY ROOTDIR ${PROJECT_SOURCE_DIR})
set_property(GLOBAL PROPERTY LIBDIR ${PROJECT_SOURCE_DIR}/lib)
set_property(GLOBAL PROPERTY RESDIR ${PROJECT_SOURCE_DIR}/resources)
set_property(GLOBAL PROPERTY APPDIR ${PROJECT_SOURCE_DIR}/app)