#define QUIT_ROUTINE()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
  if(this->quitRequested)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
      wxGetApp().CallAfter([this] {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \
        this->workerThread.join();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
        this->processing    = false;                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
        this->quitRequested = false;                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
        this->Destroy();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
      });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
      return;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
    }